# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0002_colegio'),
        ('hojadevida', '0005_auto_20170116_2334'),
        ('curriculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField()),
                ('ini', models.IntegerField()),
                ('fin', models.IntegerField()),
                ('horas', models.IntegerField()),
                ('anio', models.IntegerField(default=2017, verbose_name='A\xf1o')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo.Curso', verbose_name='Curso')),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.Configuracion')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo.Materia', verbose_name='Materia')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hojadevida.Profesor', verbose_name='Profesor')),
            ],
        ),
    ]
