# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 18:19
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acudiente',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fecha', models.DateField(verbose_name='* Fecha de Nacimiento')),
                ('sexo', models.BooleanField(choices=[(True, 'Hombre'), (False, 'Mujer')], default=True, verbose_name='* Sexo')),
                ('identificacion', models.CharField(max_length=200, unique=True, verbose_name='* Identificaci\xf3n')),
                ('telefono', models.IntegerField(verbose_name='* Telefono')),
                ('direcion', models.CharField(max_length=400, verbose_name='* Direcci\xf3n')),
                ('status', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='MultimediaData/acudiente')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AsiganacionSede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(verbose_name='A\xf1o')),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fecha', models.DateField(verbose_name='* Fecha de Nacimiento')),
                ('sexo', models.BooleanField(choices=[(True, 'Hombre'), (False, 'Mujer')], default=True, verbose_name='* Sexo')),
                ('identificacion', models.CharField(max_length=200, unique=True, verbose_name='* Identificaci\xf3n')),
                ('telefono', models.IntegerField(verbose_name='* Telefono')),
                ('direcion', models.CharField(max_length=400, verbose_name='* Direcci\xf3n')),
                ('status', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='MultimediaData/estudiante')),
                ('codigo_Estudiante', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Codigo de Estudiante')),
                ('colegio_Anterior', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='GradoEntrante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fecha', models.DateField(verbose_name='* Fecha de Nacimiento')),
                ('sexo', models.BooleanField(choices=[(True, 'Hombre'), (False, 'Mujer')], default=True, verbose_name='* Sexo')),
                ('identificacion', models.CharField(max_length=200, unique=True, verbose_name='* Identificaci\xf3n')),
                ('telefono', models.IntegerField(verbose_name='* Telefono')),
                ('direcion', models.CharField(max_length=400, verbose_name='* Direcci\xf3n')),
                ('status', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='MultimediaData/estudiante')),
                ('hoja_vida', models.FileField(blank=True, null=True, upload_to='MultimediaData/hoja_vida', verbose_name='Hoja de Vida')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hojadevida.GradoEntrante', verbose_name='*Curso de ingreso'),
        ),
        migrations.AddField(
            model_name='asiganacionsede',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hojadevida.Profesor'),
        ),
        migrations.AddField(
            model_name='asiganacionsede',
            name='sede',
            field=models.ManyToManyField(to='configuracion.Sede'),
        ),
        migrations.AddField(
            model_name='acudiente',
            name='estudiantes',
            field=models.ManyToManyField(to='hojadevida.Estudiante'),
        ),
    ]
