# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acudiente',
            old_name='direcion',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='direcion',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='direcion',
            new_name='direccion',
        ),
    ]
