# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0002_auto_20170104_2007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acudiente',
            options={'verbose_name': 'Acudiente', 'verbose_name_plural': 'Acudientes'},
        ),
        migrations.AlterModelOptions(
            name='asiganacionsede',
            options={'verbose_name': 'Asignaci\xf3n de sede', 'verbose_name_plural': 'Asignaciones de sede'},
        ),
        migrations.AlterModelOptions(
            name='estudiante',
            options={'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AddField(
            model_name='acudiente',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profesor',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
