# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0003_auto_20170105_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acudiente',
            name='telefono',
            field=models.CharField(max_length=10, verbose_name='* Telefono'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='telefono',
            field=models.CharField(max_length=10, verbose_name='* Telefono'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='telefono',
            field=models.CharField(max_length=10, verbose_name='* Telefono'),
        ),
    ]
