# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
        ('hojadevida', '0004_auto_20170105_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionSede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(default=2017, verbose_name='A\xf1o')),
                ('estado', models.BooleanField(default=True)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hojadevida.Profesor')),
                ('sede', models.ManyToManyField(to='configuracion.Sede')),
            ],
            options={
                'verbose_name': 'Asignaci\xf3n de sede',
                'verbose_name_plural': 'Asignaciones de sede',
            },
        ),
        migrations.RemoveField(
            model_name='asiganacionsede',
            name='profesor',
        ),
        migrations.RemoveField(
            model_name='asiganacionsede',
            name='sede',
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='codigo_Estudiante',
            field=models.CharField(default=1, max_length=200, unique=True, verbose_name='Codigo de Estudiante'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AsiganacionSede',
        ),
    ]
