# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hojadevida', '0005_auto_20170116_2334'),
        ('configuracion', '0002_colegio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('canhora', models.IntegerField(verbose_name='Cantidad de Horas')),
                ('profesores', models.ManyToManyField(to='hojadevida.Profesor')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_asignadas', models.IntegerField(verbose_name='Horas Asignadas')),
                ('anio', models.IntegerField(default=2017, verbose_name='A\xf1o')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['anio'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('anio', models.IntegerField(default=2017, verbose_name='A\xf1o')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hojadevida.Profesor', verbose_name='Director de Grupo')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10, unique=True)),
                ('valor', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo.Area')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo.Grado'),
        ),
        migrations.AddField(
            model_name='curso',
            name='jornada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.Configuracion'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo.Grado'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo.Materia'),
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together=set([('nombre', 'grado', 'jornada', 'director', 'anio'), ('nombre', 'grado', 'jornada', 'anio')]),
        ),
        migrations.AlterUniqueTogether(
            name='asignacion',
            unique_together=set([('grado', 'materia', 'anio')]),
        ),
    ]
