# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0002_area_eliminado'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='curso',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grado',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='materia',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
