# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 22:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0003_auto_20170127_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='eliminado',
        ),
    ]
