# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornada', models.IntegerField(choices=[(1, 'Diurna'), (2, 'Tarde'), (3, 'Nocturna')], default=1, verbose_name='*Jornada')),
                ('horaIni', models.IntegerField(choices=[(1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12')], default=7, verbose_name='*Horas de inicio de clase')),
                ('miniIni', models.IntegerField(choices=[(0, '00'), (1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31'), (32, '32'), (33, '33'), (34, '34'), (35, '35'), (36, '36'), (37, '37'), (38, '38'), (39, '39'), (40, '40'), (41, '41'), (42, '42'), (43, '43'), (44, '44'), (45, '45'), (46, '46'), (47, '47'), (48, '48'), (49, '49'), (50, '50'), (51, '51'), (52, '52'), (53, '53'), (54, '54'), (55, '55'), (56, '56'), (57, '57'), (58, '58'), (59, '59')], default=0, verbose_name='*Minutos de inicio de clase')),
                ('nothora', models.IntegerField(choices=[(0, 'am'), (1, 'pm')], default=0, verbose_name='*Notacion de la hora ')),
                ('desIni', models.IntegerField(choices=[(1, 'Primera'), (2, 'Segunda'), (3, 'Tercera'), (4, 'Cuarta'), (5, 'Quinta'), (6, 'Sexta'), (7, 'Septima'), (8, 'Octava'), (9, 'Novena'), (10, 'Decima'), (11, 'Decima Primera'), (12, 'Decima segunda')], default=4, verbose_name='*Inicio descanso al finalizar la hora')),
                ('horaDia', models.IntegerField(verbose_name='*Valor hora academica en minutos')),
                ('cantidaHora', models.IntegerField(verbose_name='*Cantidad de Horas al d\xeda')),
                ('minutos_descanso', models.IntegerField(verbose_name='*Cantidad minutos descanso')),
                ('ano', models.IntegerField(choices=[(2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024')])),
                ('hora_ini_sec_1', models.CharField(max_length=200)),
                ('hora_fin_sec_1', models.CharField(max_length=200)),
                ('hora_ini_sec_2', models.CharField(max_length=200)),
                ('hora_fin_sec_2', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionPeriodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad de Periodos Academicos')),
                ('inicio', models.DateField(verbose_name='Inicio del Periodo Academico')),
                ('fin', models.DateField(verbose_name='Fin del Periodo Academico')),
            ],
        ),
        migrations.CreateModel(
            name='Descanso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.IntegerField()),
                ('minutos', models.IntegerField()),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.Configuracion')),
            ],
        ),
        migrations.CreateModel(
            name='FechaPeriodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField(verbose_name='* Inicio de periodos ')),
                ('fin', models.DateField(verbose_name='* Fin de periodos ')),
            ],
        ),
        migrations.CreateModel(
            name='MaxMinGrado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Numero de grado minimo')),
                ('cantidad2', models.IntegerField(verbose_name='Numero de grado maximo')),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreP', models.IntegerField(verbose_name='Nombre')),
                ('inicio', models.DateField(null=True)),
                ('fin', models.DateField(null=True)),
                ('porcentaje', models.FloatField(verbose_name='Porcenaje')),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.ConfiguracionPeriodo')),
            ],
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Numero de estudiantes por salon')),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('registro', models.CharField(max_length=200, verbose_name='Registro Dane')),
                ('direccion', models.TextField(max_length=400, verbose_name='Direcci\xf3n')),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='configuracion',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.Sede', verbose_name='*Sede'),
        ),
    ]
