# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=800)),
                ('registro', models.CharField(max_length=900)),
                ('nombre', models.CharField(max_length=800)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
