# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_colegio'),
    ]

    operations = [
        migrations.AddField(
            model_name='colegio',
            name='jornada',
            field=models.IntegerField(choices=[(1, 'Unica'), (2, 'Multiples')], default=1, verbose_name='Tipo de jornadas'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Unico'), (2, 'Multiples')], default=1, verbose_name='Tipo de colegio'),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='year',
            field=models.IntegerField(verbose_name='A\xf1o'),
        ),
    ]
