# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_auto_20170125_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colegio',
            name='year',
            field=models.IntegerField(default=2017, verbose_name='A\xf1o'),
        ),
    ]
