# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_auto_20170125_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colegio',
            name='year',
            field=models.IntegerField(default=2017, verbose_name='A\xf1o'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='direccion',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Direcci\xf3n'),
        ),
    ]
