# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 22:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0004_auto_20170125_2139'),
        ('configuracion', '0004_auto_20170126_2214'),
    ]

    operations = [
    ]
